export const FETCH_CONTACT_REQ_SUCCESS = 'FETCH_CONTACT_REQ_SUCCESS';
export const FETCH_CONTACT_REQ_FAIL = 'FETCH_CONTACT_REQ_FAIL';

export const ACTIVE_TAB = 'ACTIVE_TAB';

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

export const DELETE_CONTACT_REQ_SUCCESS = 'DELETE_CONTACT_REQ_SUCCESS'